### ISSUE TITLE
title of milestone can be undefined?!

### ISSUE THREAD

**Issue by andreclinio** [andreclinio/gitlab-cli#3]
```
- [issue #3] Continuar com a instalação caso ocorra erro ao criar shortcut no Windows. [closed]
[Assigned to: Carlos Eduardo Leite de Andrade (caduandr)] [Milestone: 1.1.0 (closed)]
[closed at 01/12/2021] [enhancement]
[https://git.tecgraf.puc-rio.br/javautils/javautils-launcher/-/issues/3]

/home/macplinio/.nvm/versions/node/v14.16.1/lib/node_modules/@andreclinio/gitlab-cli/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
            throw err;
            ^

TypeError: Cannot read property 'title' of null
    at Milestone.get title [as title] (/home/macplinio/.nvm/versions/node/v14.16.1/lib/node_modules/@andreclinio/gitlab-cli/build/service/logic/Milestone.class.js:21:26)
    at Issue.toString (/home/macplinio/.nvm/versions/node/v14.16.1/lib/node_modules/@andreclinio/gitlab-cli/build/service/logic/Issue.class.js:71:77)
```

**Comment by andreclinio** [comment]
Not really. Issue can have no milestone... 😞
